# Generated by Django 2.1.8 on 2019-04-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hit',
            field=models.IntegerField(default=0),
        ),
    ]
